name: Sync to GitLab
on:
  push:
    branches:
      - to-nuxt-chat
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to GitLab
        run: |
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/Peacefull333/poligramm.git
          git push --force gitlab main
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
